name: Build UDT

on:
  push:
    branches:
      - main
      - gh-workflow
  pull_request:
    branches:
      - main

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Install Visual Studio 2017
        run: |
          # choco install visualstudio2017community --force
          choco install dotnet4.0
        shell: powershell

      - name: net path
        run: vswhere

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run premake '5.0.0-beta1'
        uses: eariassoto/setup-premake@v1
        with:
          version: '5.0.0-beta1'
          action: 'vs2022'
          options: '--file=UDT_DLL/premake/premake5.lua'

      - name: Compile with MSVC
        run: |
          cd UDT_DLL/premake
          # msbuild ..\.build\vs2022\UDT.sln /p:Configuration=Release /p:Platform=x64 /target:UDT # /target:UDT_cutter /target:UDT_splitter /target:UDT_timeshifter /target:UDT_merger /target:UDT_json /target:UDT_captures /target:UDT_converter /target:tut_multi_rail /target:tut_players

      - name: Compile UDT_GUI with MSVC
        run: |
          cd UDT_GUI
          msbuild UDT.sln /p:Configuration=Release /p:Platform=x64 /target:UDT

      - name: ls
        run: ls UDT_GUI/.bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-x64-release
          path: |
            UDT_DLL/.bin/vs2022/x64/release/.exe
            UDT_GUI/.bin/*.exe

  build-windows-gcc:
    if: false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MingW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc

      - name: Generate Makefiles
        shell: bash
        run: |
          cd UDT_DLL/premake
          ./gcc_generate.cmd

      - name: Compile with GCC
        shell: bash
        run: |
          cd UDT_DLL/premake
          ./gcc_compile.cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-gcc-binaries
          path: UDT_DLL/.bin

  build-linux-gcc:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Generate Makefiles
        run: |
          cd UDT_DLL/premake
          chmod +x gcc_generate.sh
          ./gcc_generate.sh

      - name: Compile with GCC
        run: |
          cd UDT_DLL/premake
          chmod +x gcc_compile.sh
          ./gcc_compile.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-gcc-binaries
          path: UDT_DLL/.bin
